baseURL = "https://sonar.ch/"
languageCode = "en-us"
title = "SONAR"

theme = "hugo-strata-theme"

sectionPagesMenu = "main"



### config for theme HUGO-STRATA-THEME

[params]
	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "SONAR"
	description = "Swiss Open Access Repository"

	# Format dates with Go's time formatting
	date_format = "02.01.2006"

	# Add read time estimates in the format "X min read"
	show_read_time = false

	# Add custom assets with their paths relative to the static folder
	custom_js   = []
	custom_css  = []


	[params.sidebar]
		# Replace the avatar with a picture of your own under static/images
		avatar = "sonar_logo_early.white_curves_web.svg"
		# Use Markdown to format the string. This works nearly all over the theme
		bio = "*\"collect, promote and preserve scholarly publications by authors affiliated with Swiss public research institutions...\"*"
		# The icons will be shown if you enter your username
		twitter = "sonardotch"
		github = "rero/sonar"
		facebook = ""

		copyright = [
			"",
			"",
			"[Credits](/credits/)"
		]

	[params.about]
		hide  = false
		title = "Swiss Open Access Repository"
		content = """
SONAR collects scientific publications from Swiss institutional repositories (IR) and international subject repositories.

<div class="homepage-promotion">
<a href="/project/">
<div class="homepage-promotion-link">
<h3>The Project</h3>
<img src="/images/noun_teamwork_1071941_modif.svg">
</div>
</a>
<a href="/service/">
<div class="homepage-promotion-link">
<h3>The Service</h3>
<img src="/images/noun_international_1670627_modif.svg">
</div>
</a>
</div>

SONAR contributes to the [Swiss national Open Access strategy](https://www.swissuniversities.ch/fr/themes/politique-des-hautes-ecoles/open-access/) and its action plan.
"""

	[params.portfolio]
		hide  = true
		title = "Recent Work"

		# The images and thumbnails are stored under static/images
		# Create and change subfolders as you like
		[[params.portfolio.gallery]]
			image = "fulls/01.jpg"
			thumb = "thumbs/01.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/02.jpg"
			thumb = "thumbs/02.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/03.jpg"
			thumb = "thumbs/03.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/04.jpg"
			thumb = "thumbs/04.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/05.jpg"
			thumb = "thumbs/05.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/06.jpg"
			thumb = "thumbs/06.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

	[params.recentposts]
		hide  = false
		title = "Recent blog posts"

	[params.contact]
		hide  = false
		title = "Stay informed"
		content = "You can subscribe to our newsletter... [add subscription form]"
		email = ""


# Menu links that appear on the left sidebar
[[menu.main]]
	name = "Home"
	url  = "/"
	weight = 10

[[menu.main]]
 	name = "The Project"
 	url  = "/project/"
 	weight = 0

[[menu.main]]
 	name = "The Service"
 	url  = "/service/"
 	weight = 0
